### PR TITLE
WeTek Hub and WeTek Play 2 fixes

### PR DESCRIPTION
**Pull request by codesnake**
Fix the following issues on WeTek Hub and WeTek Play 2:
* Garbled screen output for resolutions other than 1920x1080.
* No sound.

### CODE REVIEW

**Comment by Ntemis** [comment]
For the garble screen, fixes changes are accepted and welcome but am not sure we need a second alsa config we already have https://github.com/lakkatv/Lakka-LibreELEC/blob/master/projects/WeTek_Play_2/filesystem/usr/share/alsa/cards/AML-M8AUDIO.conf
&
https://github.com/lakkatv/Lakka-LibreELEC/blob/master/projects/WeTek_Hub/filesystem/usr/share/alsa/cards/AML-M8AUDIO.conf
I will test latest build to check and let you know
You can test too here:
http://le.builds.lakka.tv/

**Comment by Kivutar** [comment]
Thanks codesnake. Are these changes about platform_init in LibreELEC? We'd like to stay close to their master branch.

**Comment by Ntemis** [comment]
No kivutar they are not, these are specific lakka fixes

**Comment by codesnake** [comment]
@Kivutar Kodi uses framebuffer in a different away, so LibreELEC doesn't have such issue, so as @Ntemis already noted this fix is for Lakka only.

**Comment by Ntemis** [comment]
I confirm that we don't have device audio out selection in audio devices option

**Comment by Ntemis** [comment]
I think this is a Lakka issue and not device specific:
Lakka:~ # aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=AMLM8AUDIO
    AML-M8AUDIO, 
    Default Audio Device
sysdefault:CARD=AMLM8AUDIO
    AML-M8AUDIO, 
    Default Audio Device
hdmi:CARD=AMLM8AUDIO,DEV=0
    AML-M8AUDIO, 
    HDMI Audio Output

**Comment by Ntemis** [comment]
@codesnake 
Try this to confirm Lakka issue:
ssh to box with root:root
systemctl stop retroarch
nano .config/retroarch/retroarch.cfg
Ctrl+w search for audio_device change to -> audio_device = "hdmi:CARD=AMLM8AUDIO,DEV=0"
save and systemctl stop retroarch
restart box , voila! audio device selection is there now

**Comment by Kivutar** [comment]
OK, so we merge this?

**Comment by Kivutar** [comment]
@gouchi any idea why these devices don't get listed in RetroArch settings?

**Comment by Ntemis** [comment]
You want to merge as a temporary fix and when you fix it we can remove the second config?
All amlogic devices have this issue afaik

**Pull request merged**
